name: Deploy to MonsterASP

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_PATH: ${{ secrets.PROJECT_NAME }}
  PUBLISH_PROFILE: 'Release'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
    
    - name: Build project
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration ${{ env.PUBLISH_PROFILE }}
    
    - name: Run tests
      run: dotnet test ${{ env.PROJECT_PATH }} --no-build --configuration ${{ env.PUBLISH_PROFILE }} --verbosity normal
      continue-on-error: true
    
    - name: Publish application
      run: dotnet publish ${{ env.PROJECT_PATH }} --no-build --configuration ${{ env.PUBLISH_PROFILE }} --output ./publish
    
    - name: Create build info
      run: |
        $buildInfo = @{
          "BuildDate" = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
          "CommitHash" = "${{ github.sha }}"
          "Branch" = "${{ github.ref_name }}"
        } | ConvertTo-Json
        $buildInfo | Out-File -FilePath ./publish/build-info.json -Encoding UTF8
      shell: pwsh
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-app
        path: ./publish
        retention-days: 5

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dotnet-app
        path: ./publish
    
    - name: Display deployment files
      run: |
        echo "Files to deploy:"
        ls -la ./publish
        
    - name: Deploy to MonsterASP via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.MONSTERASP_FTP_SERVER }}
        username: ${{ secrets.MONSTERASP_FTP_USERNAME }}
        password: ${{ secrets.MONSTERASP_FTP_PASSWORD }}
        local-dir: ./publish/
        server-dir: /
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/*.pdb
        dangerous-clean-slate: false
        
    - name: Deployment Complete
      run: |
        echo "Successfully deployed to MonsterASP!"
        echo "Build Info: $(cat ./publish/build-info.json)"